config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "flats#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]



  def index
    @flats = Flat.all
  end

  def show
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1><%= "All our Flats (#{@flats.length})" %></h1>





<div class="container mx-0">
<div class="row justify-content-md-center">
<% @flats.each do |flat| %>
<div class="card col-4 my-2">
  <img src="https://loremflickr.com/320/240/<%=flat.address.split(' ').last%>" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title"><%= flat.name  %></h5>
    <p class="card-text"><%= "#{flat.description.first(150)}..."%></p>
    <p class="card-text"><i class="fa-solid fa-person"></i>  <%=flat.number_of_guests%>  <i class="fa-solid fa-euro-sign"></i>  <%=flat.price_per_night%></p>
    <div class="btn btn-primary"><p><%= link_to "More info", flat_path(flat) %></p></div>
  </div>
</div>
<% end %>
</div>
</div>

app/views/flats/show.html.erb
<h2><%= @flat.name %></h2>
<p><%= @flat.address %></p>
<p><%= @flat.description %></p>
<p><%= @flat.price_per_night %></p>
<p><%= @flat.number_of_guests %></p>


<%= link_to "Back to flat list", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>